export { default as Home } from './Home/Home';
export { default as About } from './About/About';
export { default as ServicesPage } from './Services/ServicesPage';
export { default as Career } from './Career/Career';
export { default as CareerDetail } from './Career/CareerDetail/CareerDetail';
export { default as Blog } from './Blog/Blog';
export { default as BlogDetail } from './BlogDetail/BlogDetail';
export { default as Contact } from './Contact/Contact';
export { default as TermsConditions } from './TermsConditions/TermsConditions';
