stages:
  - humanx

humanx:
  image: alpine:latest
  stage: humanx
  before_script:
    - apk update && apk add openssh-client
    - eval $(ssh-agent -s)
    - echo "$SSH_KEY_HUMANX" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
  script:
    - ssh -o StrictHostKeyChecking=no $SERVER_USER_HUMANX@$SERVER_IP_HUMANX "cd /home/kantipu6/humanx-frontend && source deploy.sh && exit"
  only:
    - main
